FROM node:20.12.2
WORKDIR /app

COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

RUN npm ci

COPY app/. .
COPY services/caddy/Caddyfile /etc/caddy/Caddyfile

EXPOSE 8080
ENV NODE_ENV=production
RUN make build

CMD make start