version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'sleep 3 && make dev'
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app"

  caddy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy:/etc/caddy
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config: